project:
  type: website
  output-dir: _site
  resources:
    - js
    - data

website:
  title: "ggsegverse"
  description: "Gross Geometry Brain Segmentation Universe"
  site-url: https://ggsegverse.github.io
  repo-url: https://github.com/ggsegverse/ggsegverse.github.io
  repo-actions: [edit, issue]
  favicon: images/favico.png

  navbar:
    title: ""
    left:
      - text: "Ecosystem"
        href: ecosystem/index.qmd
      - text: "Playground"
        href: playground/index.qmd
      - text: "Docs"
        href: docs/index.qmd
      - text: "News"
        href: news/index.qmd
      - text: "About"
        menu:
          - text: "Research using ggseg"
            href: citations/index.qmd
          - text: "Contributors"
            href: contributors/index.qmd
          - text: "Funding"
            href: funding/index.qmd
    right:
      - icon: rss
        href: news/index.xml
        aria-label: RSS Feed
      - icon: chat-dots
        href: https://github.com/orgs/ggsegverse/discussions
        aria-label: Discussions
      - icon: github
        href: https://github.com/ggsegverse
        aria-label: GitHub

  page-footer:
    left: |
      Made with [Quarto](https://quarto.org/)
    center: |
      ggsegverse &copy; 2026
    right:
      - icon: github
        href: https://github.com/ggsegverse

brand: _brand.yml

format:
  html:
    theme: [styles.scss]
    theme-toggle: true
    toc: false
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
